### PR TITLE
Fix distances in CSV files

### PR DESCRIPTION
**Pull request by alexdewar**
It seems that the distances might actually have been in km rather than m in the first place! I thought I'd adjusted the CSV files appropriately already, but it seems that we're still about a factor of 1000 out.

Have I missed something here @tnownoty? Did the distances seem sensible in your analysis?

### CODE REVIEW

**Comment by alexdewar** [comment]
I should say that after this latest adjustment I get lengths of e.g. 400000 mm, which seems about the right order of magnitude.

I'm guessing that someone accidentally divided a value in m by 1000 rather than multiplying by 1000 somewhere and that's how we ended up 6 orders of magnitude out.

**Comment by alexdewar** [comment]
Wait... I'm an idiot :facepalm:. My code converts it to m so it was fine before...

**Comment by tnowotny** [comment]
I *think* you converted to mm earlier and I made sure the scripts worked afterwards ... so as far as I am concerned, everything is fine?

**Comment by alexdewar** [comment]
Yeah I think it's fine too now. I forgot that my analysis scripts convert the distances back to m again at some point :laughing:

**Comment by alexdewar** [comment]
Reopening because I think the distances might be wrong after all!

**Pull request merged**
